In [1]:
m = 2;  n = 3;
v = [1:6;]

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

The unvec operation:

In [2]:
V = reshape(v,2,3)   

2×3 Array{Int64,2}:
 1  3  5
 2  4  6

Two equivalent syntaxes for the vec operation:

In [3]:
vec(V) 

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [4]:
V[:]                 

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6